name: Manage Labels

on:
  push:
  pull_request:
    types: [synchronize]

permissions:
  issues: triage
  pull-requests: triage
  contents: triage

jobs:
  label-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Label merge conflicts
        uses: TheGiraffe3/actions-label-merge-conflict@3.0.4
        with:
          dirtyLabel: "has conflicts"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
